name: GitHub Actions CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: +test +test-fail
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      EARTHLY_CONVERSION_PARALLELISM: "5"
    steps:
      - uses: alexcb/actions/setup-earthly@9b6a11560de3eb6a1a87eb68e1938a1db88b9755
      - name: what version is installed?
        run: ls -la / && earthly --version
